### ISSUE TITLE
Colab

### ISSUE THREAD

**Issue by iamnoob1** [mpariente/asteroid#101]
Colab notebookkk pls

**Comment by mpariente** [comment]
What do you want in the notebook? If you're not specific, we cannot help.
Did you see [those](https://github.com/mpariente/asteroid/tree/master/examples)?

**Comment by iamnoob1** [comment]
Source separation with my file

**Comment by mpariente** [comment]
When we release some models, we'll be able to have a separation engine, colab or else. I'll let you know.
