### ISSUE TITLE
ConvTasNet model can not handle long duration wav files

### ISSUE THREAD

**Issue by tux-coder** [mpariente/asteroid#140]
Hello,

ConvTasNet model can not handle long duration wav files as input, 
if the wav has a duration greater than 2 minutes then a crash will occur during the evaluation step : 

- cuda error (if GPU is used)
- segmentation fault (if CPU mode is used)

**Comment by mpariente** [comment]
Yeah, that's a memory problem on GPU and a nn.Conv1d problem on CPU. 
We should foward in chunks and combine them. 
Would you like to give it a try?

**Comment by tux-coder** [comment]
I don't know pytorch, I can try but not sure to succeed.

**Comment by mpariente** [comment]
It's not really pytorch related, it's signal processing. It would be kind of an chunk, enhance, overlap add strategy but with very long frames.
You can have a look at `torch.fold` and `torch.unfold`, I guess they would help !

**Comment by mpariente** [comment]
Refs #193

**Comment by popcornell** [comment]
We added an overlap add wrapper which makes it possible to do inference on long files without going OOM. 
See: https://github.com/mpariente/asteroid/pull/193. Once merged this issue will close.
