### ISSUE TITLE
invalid syntax at ConvTasNet

### ISSUE THREAD

**Issue by ntyoshi** [mpariente/asteroid#155]
My environment:
- Ubuntu 14.04
- Python 3.7.7

When I tried ConvTasNet, I got an error at Stage3 below:
```
Stage 3: Training
  File "train.py", line 50
    model = ConvTasNet(**conf['filterbank'], **conf['masknet'])
                                           ^
SyntaxError: invalid syntax
```
Basically the code should be ok because I hadn't changed any codes of train.py.
Does anyone have any idea of solution?

**Comment by ntyoshi** [comment]
I found my python path was wrong. It specified python 2.7.
After modifying the path, it worked.

**Comment by mpariente** [comment]
Thanks for reporting the bug and finding the solution !
