### ISSUE TITLE
pytorch-lightning deprecations

### ISSUE THREAD

**Issue by jonashaag** [mpariente/asteroid#158]
## 🐛 Bug

`Trainer()` argument name changes in 0.8:

- `max_nb_epoch` -> `max_epoch`
- `default_save_path` -> `default_root_dir`

Either pin `pytorch-lightning<0.8` or change the names.

**Comment by mpariente** [comment]
Thanks for reporting this ! 
Are those deprecated already? Or `DeprecationWarning` is thrown? 

I intended to upgrade to 0.8.1 because they have new features that will be helpful. 
I'll do this pretty soon.

**Comment by jonashaag** [comment]
They are removed in 0.8

**Comment by mpariente** [comment]
Ok thanks !

**Comment by mpariente** [comment]
I let you make a PR in setup.py and requirements? 
For now, let's pin it

**Comment by mpariente** [comment]
Closed by #159 
Thanks Jonas
