### ISSUE TITLE
Have you tried distributed training with ddp parameters?

### ISSUE THREAD

**Issue by JusperLee** [mpariente/asteroid#168]
I looked at your code and found that the default parameter of the method you implemented is dp. I used ddp as the parameter of the distributed method, and found that the result was much worse. Do you have this situation?

**Comment by mpariente** [comment]
I remember training DPRNN with ddp backend once and getting pretty decent results? 
What else did you change? Which model? etc.. 
More info can help me answer better.

**Comment by JusperLee** [comment]
This is my problem, I have solved it. Thank you.
I still have a question to ask, why DynamicMixing's mix production uses mean instead of sum.
![image](https://user-images.githubusercontent.com/33806018/88089531-ba6aaf00-cbbe-11ea-8588-a0d9e578f88c.png)
@popcornell

**Comment by popcornell** [comment]
Because I did not pay attention. 
Good catch. I think it is an error. 
As long as you use SI-SDR it will not do much difference however.
If you care about signal amplitude also and you use mixture consistency it would be a problem so we should fix it.

**Comment by popcornell** [comment]
The parameters are determined by using utils/get_training_stats.py. 
Basically we use a normal distribution because it appears that WHAM sources have a 2d gaussian distribution.
You can try running that script and see yourself the 2d histogram for sources amplitude.

**Comment by JusperLee** [comment]
If I only use dynamic mixing for wsj0, can I mix with this script to generate mix signals?

**Comment by popcornell** [comment]
Yes sure in fact it uses directly WSJ0 for producing the augmented examples. Make sure that you don't use WHAM by setting orig_percentage to 0.
 Also I think distribution for sources amplitude is the same between clean WHAM and WSJ0-2mix. You can check it with the script by plotting the histogram.

**Comment by JusperLee** [comment]
Thank you very much for your answer.
