### ISSUE TITLE
Error in Training ConvTasNet on LibriMix

### ISSUE THREAD

**Issue by subhanjansaha** [mpariente/asteroid#171]
### To Reproduce
After having created all mixtures and moving onto stage 1 of run.sh, the following errors show up -

```
Stage 1: Training
Traceback (most recent call last):
  File "train.py", line 127, in <module>
{'data': {'n_src': 3,
          'sample_rate': 16000,
          'segment': 3,
          'task': 'sep_noisy',
          'train_dir': 'data/wav8k/min/train-360',
          'valid_dir': 'data/wav8k/min/dev'},
 'filterbank': {'kernel_size': 16, 'n_filters': 512, 'stride': 8},
 'main_args': {'exp_dir': 'exp/train_convtasnet_84932317', 'help': None},
 'masknet': {'bn_chan': 128,
             'hid_chan': 512,
             'mask_act': 'relu',
             'n_blocks': 8,
             'n_repeats': 3,
             'skip_chan': 128},
 'optim': {'lr': 0.001, 'optimizer': 'adam', 'weight_decay': 0.0},
 'positional arguments': {},
 'training': {'batch_size': 24,
              'early_stop': True,
              'epochs': 200,
              'half_lr': True,
              'num_workers': 4}}
    main(arg_dic)
  File "train.py", line 33, in main
    segment=conf['data']['segment'])
  File "/home/subhanjan/asteroid/asteroid/data/librimix_dataset.py", line 52, in __init__
    md_file = [f for f in os.listdir(csv_dir) if 'both' in f][0]
FileNotFoundError: [Errno 2] No such file or directory: 'data/wav8k/min/train-360'
```

### Expected behavior

I have been trying to train ConvTasNet on n_src=3 for a while now and since LibriMix has this feature conveniently built in, I have been trying to use that, but I have been running into errors with the train_dir, test_dir variables in run.sh. Do they need to be changed? They're being parsed as .csv files so what should these paths be changed to.

### Environment
This is what my run.sh looks like

```
storage_dir=../LibriMix3spk

# After running the recipe a first time, you can run it from stage 3 directly to train new models.

# Path to the python you'll use for the experiment. Defaults to the current python
# You can run ./utils/prepare_python_env.sh to create a suitable python environment, paste the output here.
python_path=python

# Example usage
# ./run.sh --stage 3 --tag my_tag --task sep_noisy --id 0,1

# General
stage=0  # Controls from which stage to start
tag=""  # Controls the directory name associated to the experiment
# You can ask for several GPUs using id (passed to CUDA_VISIBLE_DEVICES)
id=0
out_dir=librimix # Controls the directory name associated to the evaluation results inside the experiment directory

# Network config
n_blocks=8
n_repeats=3
mask_act=relu
# Training config
epochs=200
batch_size=24
num_workers=4
half_lr=yes
early_stop=yes
# Optim config
optimizer=adam
lr=0.001
weight_decay=0.
# Data config
train_dir=data/wav8k/min/train-360
valid_dir=data/wav8k/min/dev
test_dir=data/wav8k/min/test
sample_rate=16000
n_src=3
segment=3
task=sep_noisy  # one of 'enh_single', 'enh_both', 'sep_clean', 'sep_noisy'
```
Kindly consider making run.sh more user-friendly and modular, since it's the user's only way of interacting with the program.

**Comment by subhanjansaha** [comment]
I have tried changing `data/wav8k/min/train-360` to `~/asteroid/egs/librimix/ConvTasNet/LibriMix3spk/Libri3Mix/wav8k/min/train-360/` (which is where prepare_data.sh has created and saved the mixtures). However, like I said, `$test_dir` is supposed to be parsed as a .csv so I am running into more errors. I can attach the stack trace, if required

**Comment by mpariente** [comment]
@JorisCos could you look into that please?

**Comment by JorisCos** [comment]
Hello @subhanjansaha thank for reporting your issue. 
I have tried to replicate your issue but the `/data` directory was created in the right place for me. 
Usually, everything happens  in the directory `/asteroid/egs/librimix/ConvTasNet/` from there you run `./run.sh` and everything should work fine. 
In your case, the `/data` directory was created in `/asteroid/egs/librimix/ConvTasNet/local`  but it should have been created in ``/asteroid/egs/librimix/ConvTasNet/``. 
Did you run `./run.sh` from ``/asteroid/egs/librimix/ConvTasNet/`` or did you run `prepare_data.sh` from the `/asteroid/egs/librimix/ConvTasNet/local` directory ?
From my understanding the `storage_dir` that you used to generate the mixtures is `/asteroid/egs/librimix/ConvTasNet/LibriMix3spk/` right ?
If I'm right, `/asteroid/egs/librimix/ConvTasNet/LibriMix3spk/Libri3Mix/wav8k/min/train-360/` actually contains .wav files not csv so you shouldn't change  `data/wav8k/min/train-360` to `~/asteroid/egs/librimix/ConvTasNet/LibriMix3spk/Libri3Mix/wav8k/min/train-360/`
What you should try is to simply move the `/data` folder from `/asteroid/egs/librimix/ConvTasNet/local` to `/asteroid/egs/librimix/ConvTasNet/` and go back to the original code where `$train_dir` `test_dir` `valid_dir` are given correctly.
Don't hesitate to ask if you still have an issue or if I wasn't clear enough :)

**Comment by mpariente** [comment]
Good catch @JorisCos , `prepare_data.sh` was probably ran from `./local` and that would explain the problem !

**Comment by subhanjansaha** [comment]
@JorisCos Yes, the `data` directory was generated within the `local` directory for me for some reason. However, I can assure you I did not run `prepare_data.sh` directly from the `local` dir. It was called as a part of the `run.sh` code, but all I did was run `run.sh`

**Comment by mpariente** [comment]
Could you please try to re-run the data prep to see if the problem persists please? 
We tried this morning and it worked as expected.

**Comment by JorisCos** [comment]
> @JorisCos Yes, the `data` directory was generated within the `local` directory for me for some reason. However, I can assure you I did not run `prepare_data.sh` directly from the `local` dir. It was called as a part of the `run.sh` code, but all I did was run `run.sh`

Ok can you try as @mpariente suggested  to re run `run.sh` with the right storage_dir (the same as the one you specified when you ran `run.sh` for the first time) but before running it you should edit the `prepare_data.sh ` like so 

```
#!/bin/bash

storage_dir=
n_src=
python_path=python

. ./utils/parse_options.sh

current_dir=$(pwd)
## Clone LibriMix repo
#git clone https://github.com/JorisCos/LibriMix
#
## Run generation script
#cd LibriMix
#. generate_librimix.sh $storage_dir

cd $current_dir
$python_path local/create_local_metadata.py --librimix_dir $storage_dir/Libri$n_src"Mix"
```

to avoid redownloading everything

**Comment by mpariente** [comment]
Any news @subhanjansaha ?
Thanks

**Comment by mancomao** [comment]
@mpariente @subhanjansaha @JorisCos   

Hi guys,  I encountered the same issue,  and it's a bug in this place:
https://github.com/asteroid-team/asteroid/blob/master/egs/librimix/ConvTasNet/local/prepare_data.sh#L13

change this line to 
changed_n_src=$n_src,   or local/create_local_metadata.py can't find the right root libri directory. 

thanks
