### ISSUE TITLE
set -e not working?

### ISSUE THREAD

**Issue by jonashaag** [mpariente/asteroid#181]
In ConvTasNet `run.sh`, there's a `set -e` at the start of the file, so I'd expect the `run.sh` script to stop for instance if training has failed. But for me it always "falls through" to the next step, e.g. evaluation, which then fails because training hasn't completed.

**Comment by popcornell** [comment]
It is not only for you I confirm I have the same issue.

**Comment by mpariente** [comment]
Same here, I looked (a bit) at how to propagate the error from python to bash but didn't find the obvious way.
I don't know much about exist codes in python but we could probably use that to communicate the outcome to bash, IDK.

**Comment by jonashaag** [comment]
Aha, it misses `-o pipefail`. See https://stackoverflow.com/a/6872163

**Comment by jonashaag** [comment]
See #182
