### ISSUE TITLE
Convert sphere format to wav format  find: unknown predicate `--wav_dir'

### ISSUE THREAD

**Issue by liziru** [mpariente/asteroid#202]
After I installed the dependency following the instructions, I ran './run.sh --stage 0 --tag first --task sep_noisy --id 0' to start but found this  problem:
`/home/dell/users/lpp/ss/asteroid-master/egs/wham/ConvTasNet
Convert sphere format to wav format
find: unknown predicate `--wav_dir'`

So I print the sphere_dir and wav_dir in convert_sphere2wav.sh, found the 'Sphere_dir' is '--wav_dir' and 'wav_dir' is empty:
`Sphere_dir: --wav_dir
wav_dir:`
I am confused now. Should I fill the 'sphere_dir' in run.sh？ And what should i fill? Or why the readme not tell this? 

I will appreciate it for any help.

**Comment by mpariente** [comment]
Can you please show me the top of the `run.sh` file?

**Comment by liziru** [comment]
> Can you please show me the top of the `run.sh` file and the exact command you ran?

`#!/bin/bash

# Exit on error
set -e
set -o pipefail

# Main storage directory. You'll need disk space to dump the WHAM mixtures and the wsj0 wav
# files if you start from sphere files.
storage_dir=

# If you start from the sphere files, specify the path to the directory and start from stage 0
sphere_dir=  # Directory containing sphere files
# If you already have wsj0 wav files, specify the path to the directory here and start from stage 1
wsj0_wav_dir=
# If you already have the WHAM mixtures, specify the path to the directory here and start from stage 2
wham_wav_dir=
# After running the recipe a first time, you can run it from stage 3 directly to train new models.`

**Comment by liziru** [comment]
> Can you please show me the top of the `run.sh` file and the exact command you ran?

Actually, i donot kown how to fill 'sphere_dir' .

**Comment by mpariente** [comment]
Do you have the wsj0 data? 
(Please use triple quotes ``` for  blocks of code)

**Comment by liziru** [comment]
> Do you have the wsj0 data?
> (Please use triple quotes ``` for blocks of code)

OK, I see. I donot have waj0 dataset. Is this the key to this problem? But I cannot find this dataset. Would you like to share the dataset with me? I will appreciate it very much.

**Comment by mpariente** [comment]
It's under license, I can't. 
Have a look at LibriMix instead

**Comment by liziru** [comment]
> It's under license, I can't.
> Have a look at LibriMix instead

OK. If I start from the sphere files, Do I still need wjs0 dataset ?

**Comment by liziru** [comment]
Or wjs0 is made of sphere files?
