### ISSUE TITLE
problems with mixed precision training 

### ISSUE THREAD

**Issue by popcornell** [mpariente/asteroid#213]
## 🐛 Bug

see https://github.com/PyTorchLightning/pytorch-lightning/issues/2343

right now having overrided the optimizer_step because of  schedulers mixed precision does not work.

**Comment by mpariente** [comment]
Should be fixed in 0.9.0 then, cool !

**Comment by mpariente** [comment]
Does this work now?

**Comment by popcornell** [comment]
Yes it works now closing this
