### ISSUE TITLE
A attribute in Encoder is not defined

### ISSUE THREAD

**Issue by zwb0626** [mpariente/asteroid#225]
I am running the train.py in egs/wham/FilterbankDesign  But the console warning me that the Encoder has no attribute apply_mask( in model.py 30 line).  And some attribute like encoder.inp_mode and encoder.mask_mode(model.py line 15 16)looks like not be used and i annotate it ,is that right?

Thank you

**Comment by mpariente** [comment]
The Filterbank design egs is actually not complete.. 
But starting from the ConvTasNet recipe and parameterizing the `fb_name`, that should be easy to get.

**Comment by mpariente** [comment]
We're in the process of refactoring the recipes, we'll get back to polishing the existing ones when this is done. 
Sorry but the filterbank design recipe is actually the only deprecated one.

**Comment by zwb0626** [comment]
Ok,thanks for your help
