### ISSUE TITLE
Windowing for analytic free filterbank

### ISSUE THREAD

**Issue by lminer** [mpariente/asteroid#251]
In section 2.2 of your paper "FILTERBANK DESIGN FOR END-TO-END SPEECH SEPARATION" you mention that the analytic free filterbanks should be multiplied by a hamming window, but I'm not seeing it in your implementation. Am I missing something?

**Comment by mpariente** [comment]
Thanks for opening this issue. 

The section 2.2 proposes two analytic filterbanks: 
- the extended parameterized sinc filterbank, whose filters are indeed multiplied by a window
- the analytic free filterbank, for which I don't mention windowing. 

I see now that having both filterbanks in the same section can be confusing though, sorry about that. 

Just in case, I re-read the original code that was used for the paper's experiments and there is no windowing there either. 
Also, if you look at the filters, the windowing is learned and is not the same across filters.

**Comment by lminer** [comment]
That explains a lot. Thank you!
