### ISSUE TITLE
Use 16bit training conv-tasnet results are worse

### ISSUE THREAD

**Issue by JusperLee** [mpariente/asteroid#252]
#### What is your question?
Use 16bit training conv-tasnet results are worse. The result of 32-bit training is about 1.6 better than the result of 16-bit training (SI-SNRi).
#### Code
```python
Trainer(precision=16)
```

**Comment by jonashaag** [comment]
Not a solution, but I've also seen this multiple times. For other models as well. Do you know of an example of someone successfully training speech separation networks using FP16? Maybe the range of values is just too large.

**Comment by mpariente** [comment]
Never tried myself so I can't say.. Is it consistent across runs? There is this scale incosistency in SI-SNR, not sure if that would be a cause.

If you have any elements of answer, it could be helpful

**Comment by jonashaag** [comment]
Yes, I have never gotten any good results.

**Comment by JusperLee** [comment]
I also found out when I tried it, the result would be very bad. I have not seen any successful training with FP16 yet.

**Comment by mpariente** [comment]
I'll close this. 
Feel free to re-open if needed.
