### ISSUE TITLE
Parallelise chunks in LambdaOverlapAdd

### ISSUE THREAD

**Issue by groadabike** [mpariente/asteroid#254]
## 🚀 Feature
Parallelise the chunks  processing in ola_forward from LambdaOverlapAdd by utilising N number of CPU/GPU

### Motivation
LambdaOverlapAdd is a nice function that allows to split the audio and apply a function in a small segment of this audio to then combine all with OLA.
However, it would be nice to be able to distribute these chunks on several CPU which would speed up the separation of long audios.

### What you'd like

The result should be the same that the current results, but, the function should have a parameter with the number of CPU in order to, using multiprocessing, split the job among all the requested CPUs.

**Comment by mpariente** [comment]
Indeed, this sounds like a nice idea, few points: 
- What about `_reorder_sources`? We should apply it after all chunks are processed. 
- For CPUs, I agree but copying a nnet to a new GPU takes a while no? Would we really benefit from it? 
- What would be other use cases where `LambdaOverlapAdd` would be useful? Currently, it seems well suited for processing long audio files. For other applications, it will be too inefficient because of the for loop, ideas? @popcornell @jonashaag

**Comment by jonashaag** [comment]
I think we can get an order of magnitude speedup already by using the batch dimension (at the cost of memory). We could make it configurable and maybe use a sane default (with a nice error message if we go out of memory). On CPU, I assume PyTorch will parallelise on the batch dimension automatically? On GPU, batch dimension obviously is parallelised. So, by using the batch dimension, we already have all of the speedup we can get without adding super specific code (distributed inference etc), right?

**Comment by popcornell** [comment]
We can process using the batch dimension by accumulating x batches of
overlapped segments. Then yes we need a second pass for reordering. How
much it will be faster than say process an equivalent length sequence by
using a long window? (Answer will be probably different whether a recurrent
or a convolutional architecture is used).

**Comment by jonashaag** [comment]
Batch vs. longer window aren’t really an alternative, generally speaking. Some models have fixed input size. (Maybe none of the models in Asteroid, I don’t know.) And some models may even have larger-than-linear memory requirements? Not sure.

**Comment by mpariente** [comment]
> I think we can get an order of magnitude speedup already by using the batch dimension (at the cost of memory). We could make the batch size configurable and maybe use a sane default (with a nice error message if we go out of memory). 

On GPU, the OOM will actually happen quite fast and the error will be raised. On CPU, in my experience, it'll go until using disk swap and freeze your PC/cluster and you'd rather kill the job than wait for the error. 
We'll want to avoid that, as the main purpose of this class is to enable inference on long files 

> On CPU, I assume PyTorch will parallelise on the batch dimension automatically? 

I think it'll use all the CPUs available, yes. 

> So, by using the batch dimension, we already have all of the speedup we can get without adding super specific code (distributed inference etc), right?

Indeed, we don't need to write the parallelization.


So, how would we do? Add an argument `forward_by` or `gather_by` (other ideas) that decides how many segments we include per forward?

**Comment by groadabike** [comment]
> * For CPUs, I agree but copying a nnet to a new GPU takes a while no? Would we really benefit from it?
You are right, for GPU it makes little sense, 
This would be more beneficial for CPU inferring.

**Comment by mpariente** [comment]
But I guess that if the models is already `DataParallel`, the batch paralellization would take care of dispacthing inputs.

**Comment by popcornell** [comment]
Let's go for  accumulating windows  on batch dimension then unfold to time and decode with reorder sources. 
`gather_by` makes sense or `accumulate_chunks`

**Comment by mpariente** [comment]
We need a way to specify the number of `chunks` we put in the _batch size_, the argument needs to reflect that.

**Comment by popcornell** [comment]
Also because decoding is done offline maybe we can even think of doing a two pass decoding. This is more difficult however

**Comment by mpariente** [comment]
>  doing a two pass decoding

What do you mean by that? Intra-batch reordering and then inter-batch
reordering?

**Comment by popcornell** [comment]
No i mean we can do a forward and then backward in time reordering (only advantage is for > 2 speakers)

**Comment by mpariente** [comment]
I'm going to close that, because it is not a priority IMO. 
I'm willing to accept a PR on that though @groadabike
