### ISSUE TITLE
Pretrained models don't work correctly on Asteroid 0.3.3

### ISSUE THREAD

**Issue by groadabike** [mpariente/asteroid#255]
## 🐛 Bug

It seems pre-trained models saved on different Asteroid versions are incompatible.
If using Asteroid 0.3.3, I perform some source separations using the pre-trained models from Zenodo (trained using Asteroid < 0.3.3), the estimated sources show an artefact in specific frequencies. However, The same source separation using previous Asteroid version, e.g., Asteroid 0.3.0, no artefact is present in the estimations.

Note that I was able to "fix" this problem in my case by:
1- Trained a model in an HPC cluster using Asteroid 0.3.0.
2. Copy the best checkpoint to my local computer where I have Asteroid 0.3.3.
3. In my local, save the checkpoint as  best_model.pth

### To Reproduce

**Estimation using Asteroid 0.3.0**
This [colab](https://colab.research.google.com/drive/1Z5Mlv-5VBzF5qzjVWVoKNBDYjxMCjtWH?usp=sharing) has an example of estimating sources using Asteroid=0.3.0 and Cosentino/ConvTasNet_LibriMix_sep_clean 

Image of estimated source (1)
![1](https://user-images.githubusercontent.com/17277802/93101150-d613a280-f6a1-11ea-8ab0-2b2051253545.png)

**Estimation using Asteroid 0.3.3**
This [colab](https://colab.research.google.com/drive/1ZqXQZHfr0ekuYw_uspUy4lK74wZY8G9G?usp=sharing), is similar than the previous, the only difference is now we are using Asteroid=0.3.3

Image of estimated source (1)
![2](https://user-images.githubusercontent.com/17277802/93101264-f80d2500-f6a1-11ea-946e-45782428fc6a.png)

Note that in the second image, there is an apparent artefact at 3000 Hz.
In the colab, you can hear this artefact.

### Expected behavior

The pre-trained models should be agnostic to the Asteroid version, or they should indicate under which version we know it works correctly.

### Environment

 - Asteroid Version or commit tag
 - PyTorch Version 
 - PyTorchLightning Version
 - Additional info

**Comment by mpariente** [comment]
Thanks a lot for looking into this !
I need to take time to figure this out (is it the separator or the encoder/decoder for example)

> Note that I was able to "fix" this problem in my case by:
 > 1. Trained a model in an HPC cluster using Asteroid 0.3.0.
>  2. Copy the best checkpoint to my local computer where I have Asteroid 0.3.3.
 > 3. In my local, save the checkpoint as best_model.pth

I don't see how this solves the problem.. 
In 2, you copy the file directly, and then in 3, you load and re-save in Asteroid 0.3.3?

**Comment by groadabike** [comment]
> I don't see how this solves the problem..

Sorry, I didn't mean that it is a solution. This is why I say "fix" in quotes. It was a hacky way to solve my immediate problem.

> In 2, you copy the file directly, and then in 3, you load and re-save in Asteroid 0.3.3?

That is exactly what I did. I just mentioned it because it could add some info.
For example, it seems the problem raises after serializing the model.

**Comment by mpariente** [comment]
Thanks again for raising this issue. I'll take time to look into it now. 

I didn't mean that it doesn't solve the problem, but I also don't understand how this fixes it (as a hack). Anyway, I'll try it out and see what's the problem hopefully. 

By the way, have you tried with other models?

**Comment by mpariente** [comment]
Also, were you able to "fix" the problem with the pretrained model?

**Comment by mpariente** [comment]
Ok, I spotted the issue. 
The bug was introduced in #200 because we added `encoder_activation` as an argument, and it has `"relu"` default in ConvTasNet however it was linear before. 
So, we'll have to change that, and finally, we should add consistency tests for pretrained models, this will be quite heavy..

**Comment by mpariente** [comment]
Actually, I introduced it in #204, my bad.
