### ISSUE TITLE
Can you provide train log in some examples?

### ISSUE THREAD

**Issue by ksnzh** [mpariente/asteroid#272]

**Comment by jonashaag** [comment]
Please be more specific. What do you need the info for?

**Comment by mpariente** [comment]
I think we've already talked about that and it would be great to have it, but this is low priority. 

What needs to be done is to retrieve the train and val loss from the trainer and plot the training curve (or maybe we can use tensorboard to do it locally, I don't know). Assing it on the Zenodo deposit would also be great. 

Would you like to work on it @ksnzh ?

**Comment by mpariente** [comment]
ping @ksnzh
