### ISSUE TITLE
Strange spectral rays in the output

### ISSUE THREAD

**Issue by coincoin73** [mpariente/asteroid#273]
![spectral ray](https://user-images.githubusercontent.com/59832663/95672493-dcfed980-0ba9-11eb-973d-467764c9e455.png)
First, thanks for this great job, it is very, very useful to test, evaluate, compare...

I have one question about the pretrained model (Cosentino/ConvTasNet_LibriMix_sep_noisy, mpariente/DPRNNTasNet_WHAM!_sepclean ...):
My input is 8 kHz signal. Why do I have a spectral ray at 1 kHz + all harmonics into the output ?

Thanks in advance

**Comment by mpariente** [comment]
Thanks for the kind words ! 

See #255 please. 
Can you update to 0.3.4 and see if this is still the case?

**Comment by coincoin73** [comment]
What a fool ! I forgot to look into the closed issues !!!!
Thanks for the quick answer.
I do the test right now

**Comment by coincoin73** [comment]
Works well now with the last version, thanks for your help
And sincerely, it's a very good job.
