### ISSUE TITLE
Running a recipe for baseline DNS-challenge

### ISSUE THREAD

**Issue by kssk16** [mpariente/asteroid#277]
Thanks for this nice framework!

I am trying to run a recipe for baseline DNS-challenge. The DNS-challenge repo was already present and hence I started the recipe from stage 1. Somehow the 'data/file_infos.json' file is not generated. I get the following error at line 25 of dns_dataset.py:

FileNotFoundError: [Errno 2] No such file or directory: 'data/file_infos.json'

I have checked all the folders if it is generating in a folder different to that of the dataset folder, but it is not present anywhere.

Where is this file generated? And what info does it contain?

**Comment by mpariente** [comment]
Can you try again from stage 1, this should be fixed in master now?
