### ISSUE TITLE
Is there s recipe for DCCRN?

### ISSUE THREAD

**Issue by youngsuenXMLY** [mpariente/asteroid#278]
### Before asking:   
1. search the issues.   
2. search the docs.

**Comment by jonashaag** [comment]
What dataset are you targeting?

**Comment by ksnzh** [comment]
You can just use DNS-chanllenge's baseline recipe with several modifications.

```
def make_model_and_optimizer(conf):
    """Function to define the model and optimizer for a config dictionary.
    Args:
        conf: Dictionary containing the output of hierachical argparse.
    Returns:
        model, optimizer.
    The main goal of this function is to make reloading for resuming
    and evaluation very simple.
    """
    # Make the complete model
    model = DCCRNet(**conf["filterbank"], **conf["masknet"])
    # Define optimizer of this model
    optimizer = make_optimizer(model.parameters(), **conf["optim"])
    return model, optimizer


class SimpleSystem(System):
    def common_step(self, batch, batch_nb, train):
        mixture, speech, noise = batch
        estimate = self(mixture.unsqueeze(1))
        loss = self.loss_func(estimate, speech)
        return loss
```

**Comment by jonashaag** [comment]
Note also #276

**Comment by ksnzh** [comment]
> You can just use DNS-chanllenge's baseline recipe with several modifications.
> 
> ```
> def make_model_and_optimizer(conf):
>     """Function to define the model and optimizer for a config dictionary.
>     Args:
>         conf: Dictionary containing the output of hierachical argparse.
>     Returns:
>         model, optimizer.
>     The main goal of this function is to make reloading for resuming
>     and evaluation very simple.
>     """
>     # Make the complete model
>     model = DCCRNet(**conf["filterbank"], **conf["masknet"])
>     # Define optimizer of this model
>     optimizer = make_optimizer(model.parameters(), **conf["optim"])
>     return model, optimizer
> 
> 
> class SimpleSystem(System):
>     def common_step(self, batch, batch_nb, train):
>         mixture, speech, noise = batch
>         estimate = self(mixture.unsqueeze(1))
>         loss = self.loss_func(estimate, speech)
>         return loss
> ```

Also, modify the `distance` funtion to regress the waveform directly.

```
def distance(estimate, target, is_complex=True):
    return F.l1_loss(estimate, target, reduction='mean')
```

**Comment by jonashaag** [comment]
Closing since the question seems to be answered.

**Comment by Tigerwww** [comment]
> You can just use DNS-chanllenge's baseline recipe with several modifications.
> 
> ```
> def make_model_and_optimizer(conf):
>     """Function to define the model and optimizer for a config dictionary.
>     Args:
>         conf: Dictionary containing the output of hierachical argparse.
>     Returns:
>         model, optimizer.
>     The main goal of this function is to make reloading for resuming
>     and evaluation very simple.
>     """
>     # Make the complete model
>     model = DCCRNet(**conf["filterbank"], **conf["masknet"])
>     # Define optimizer of this model
>     optimizer = make_optimizer(model.parameters(), **conf["optim"])
>     return model, optimizer
> 
> 
> class SimpleSystem(System):
>     def common_step(self, batch, batch_nb, train):
>         mixture, speech, noise = batch
>         estimate = self(mixture.unsqueeze(1))
>         loss = self.loss_func(estimate, speech)
>         return loss
> ```

When loading the `conf["masknet"]` to DCCRN, it says "unexpected keyword '`hidden_size`'". Would you please provide the conf setting of masknet for DCCRN?

**Comment by realkris** [comment]
> > You can just use DNS-chanllenge's baseline recipe with several modifications.
> > ```
> > def make_model_and_optimizer(conf):
> >     """Function to define the model and optimizer for a config dictionary.
> >     Args:
> >         conf: Dictionary containing the output of hierachical argparse.
> >     Returns:
> >         model, optimizer.
> >     The main goal of this function is to make reloading for resuming
> >     and evaluation very simple.
> >     """
> >     # Make the complete model
> >     model = DCCRNet(**conf["filterbank"], **conf["masknet"])
> >     # Define optimizer of this model
> >     optimizer = make_optimizer(model.parameters(), **conf["optim"])
> >     return model, optimizer
> > 
> > 
> > class SimpleSystem(System):
> >     def common_step(self, batch, batch_nb, train):
> >         mixture, speech, noise = batch
> >         estimate = self(mixture.unsqueeze(1))
> >         loss = self.loss_func(estimate, speech)
> >         return loss
> > ```
> 
> Also, modify the `distance` funtion to regress the waveform directly.
> 
> ```
> def distance(estimate, target, is_complex=True):
>     return F.l1_loss(estimate, target, reduction='mean')
> ```

Hi, I'm trying to implement DCCRN with your modifications, it was great, but I have several questions
1. In function distance, where does the "F" come from?
2. how can I change the channels of DCCRN? I saw there's a "_dccrn_architectures.py " seems like a config of DCRNN under asteroid/masknn, but I didn't find where it is called in model architecture.

Thank you for your help!
