### ISSUE TITLE
Add OLA support to separate() method

### ISSUE THREAD

**Issue by jonashaag** [mpariente/asteroid#279]
## 🚀 Feature

The `.separate()` method of `BaseModel` is very convenient but doesn't handle long audio files with OLA.

### Motivation

Make it easy for people to use `separate()` with audio files that are longer than the models

### Ideas

Two ideas:

1) Add OLA support to `.separate()` explicitly, i.e. params `ola_window_size`, `ola_hop_length` etc. and have it deal with OLA.

2) Move `.separate()` out of `BaseModel` to a function and have it accept any type of model, then you can just pass an OLA wrapper like this: `separate(LambdaOverlapAdd(model, window_size=...))`. This seem to work great (I have been doing that for some time now), and also means that the `.separate()` method probably shouldn't be part of `BaseModel` in the first place, as it is more generally applicable.

**Comment by mpariente** [comment]
If the method is useful by itself, it makes sense to expose it outside of `BaseModel`.
Let's say we move `separate` outside `BaseModel` then, we could still have something like this. 

```python 
class BaseModel:
    def separate(self, *args, ola_window_size=None, ola_hop_length=None):
        net = self
        if ola_window_size is not None:
            net = LambdaOverlapAdd(self, ...)
        return separate(net, *args, *kwargs)
```

One thing to consider though: for now we have only waveform-based models under `BaseModel` but some other models can require preprocessing of the input wav and postprocessing of the net output to separate input data.  This is what motivated me to bind the `separate` method to the model.

If you'd like to make a PR to implement the second option, you can go ahead and we'll solve the problems as we go.

**Comment by jonashaag** [comment]
Note to self: Also fix this https://github.com/mpariente/asteroid/blob/master/asteroid/models/base_models.py#L144 (should be before exists check)

**Comment by mpariente** [comment]
Oh yes, thanks for the catch
