### ISSUE TITLE
A questions about the implementation of DCCRN

### ISSUE THREAD

**Issue by wangtianrui** [mpariente/asteroid#280]
This repository is a very nice job, and I love it.

I have some little confusion about the implementation of “DCCRN “ in the source code. In the picture of the paper, the output of the last encoder will be “cat” into the input before the first decoder, but in the source code implemented by your team, the "cat" operation is put after the first decoder. Is it my misunderstanding or some other problems?

Thank you very much!

**Comment by jonashaag** [comment]
Please have a look at #276. If you can review the revised implementation that would be very much appreciated.

**Comment by wangtianrui** [comment]
Thank you very much for your reply.
