### ISSUE TITLE
the package about pytorch lightning

### ISSUE THREAD

**Issue by cst781** [mpariente/asteroid#282]
## 🐛 Bug
could not find the correct version of pytorch lightning since it has upgraded

### To Reproduce

Steps to reproduce the behavior (code sample and stack trace):

### Environment

 - Asteroid Version or commit tag
 - PyTorch Version (e.g., 1.0)
 - PyTorchLightning Version
 - Additional info

**Comment by jonashaag** [comment]
The version is pinned in both setup.py and requirements.txt
