### ISSUE TITLE
Clarification regarding DCCRNet

### ISSUE THREAD

**Issue by kssk16** [mpariente/asteroid#286]
Hi,
I was just going through the DCCRNet implementation and came across the below snippet of code in recurrent.py
 

     def __init__(self, in_size, hid_size=128, rnn_type="LSTM", norm_type=None):
        super().__init__()

        self.rnn = complex_nn.ComplexMultiplicationWrapper(SingleRNN, rnn_type, in_size, hid_size)
        self.linear = complex_nn.ComplexMultiplicationWrapper(nn.Linear, hid_size, in_size)
        self.norm = norms.get_complex(norm_type)

As I understand from the DCCRNet paper the dense layer has 1024 units, whereas the RNN has 256/128 hidden units. The way it is defined in the above code (same variable "hid_size" for both RNN and dense layers) both RNN and dense layers will take the same number of hidden units.

I might be wrong here but seems like a bug to me.

Could you please clarify this?

Best,
Shashi

**Comment by jonashaag** [comment]
No, look at the second parameter to Linear: it will output `in_size` params, ie. ~1k depending on the FFT.

**Comment by jonashaag** [comment]
Maybe it’s wrong anyways, please can you review this https://github.com/huyanxin/DeepComplexCRN/issues/4 and compare it with the implementation in #276 ?

**Comment by kssk16** [comment]
I am closing this issue, as the DCCRNet code is published. Thanks for the support @jonashaag :)
