### ISSUE TITLE
Why are the replications so bad?

### ISSUE THREAD

**Issue by hong1997-12** [mpariente/asteroid#287]

**Comment by hong1997-12** [comment]
I don't know what went wrong,I do not change the model and use the LibriMix database.

**Comment by mpariente** [comment]
More info?

**Comment by hong1997-12** [comment]
I use the conv-tasnet for Speech Separation on wham .I do not change the experiment configurations and network structure.I tried to implement the denoising and separation tasks on this network,but the results obtained are very different from the published results.

**Comment by jonashaag** [comment]
Please tell how exactly what are the results, what did you expect them to be, how have you obtained the results, what is your dataset, etc.

**Comment by mpariente** [comment]
> I don't know what went wrong,I do not change the model and use the LibriMix database.

> I use the conv-tasnet for Speech Separation on wham .

This doesn't seem consistent. You won't get help if you're not clear.

**Comment by mpariente** [comment]
Closing. Feel free to open a real issue, with details about your problems.
