### ISSUE TITLE
Refactoring of `DeMask` model

### ISSUE THREAD

**Issue by mhu-coder** [mpariente/asteroid#293]
### Goal
Hey guys, I was planning to refactor `DeMask` to use `BaseEncoderMaskerDecoder` so that it supports 1D input data when traced with 2D (and the other way round). Currently, a traced `DeMask` model will only work with data that has the same input shape as the example used for tracing because of the way `forward` is written.

Refactoring the class with `BaseEncoderMaskerDecoder` would automatically solve this issue in addition to cleaning the class. However I had some questions before making a whole bunch of changes (see below).

#### in `__init__`

1. When computing `n_feats_input` with `fb_type` set to `stft`, isn't the value 
```python
n_feats_input = (self.encoder.filterbank.n_filters) // 2 + 1
```
only valid for even values of `n_filters`. If it is, wouldn't we need to either support the case of odd values for `n_filters` or raise an error when `n_filters` is odd?
2. When computing `n_feats_output`, there is a check on `self.input_type`. Shouldn't it be on `self.output_type` instead? The error message also mentions "Input type" but shouldn't it be about "Output type"?

#### In `forward`

The current flow of data in the `forward` of `BaseEncoderMaskerDecoder` is as follow (written as plain text as Mermaid diagrams are not supported on GitHub yet):

```
wav -> <input shaping> -> [Encoder] -> [Encoder postprocess] -> [Encoder activation] -> tf_rep

tf_rep ->  [Masker] -> masker_outmasker_out --> [Masker postprocess] -> <mult> -> masked 
       |                                                                  1
       |------------------------------------------------------------------|
masked -> [Decoder] -> [Decoder postprocess] -> <shape output> -> reconstruction
```
where the values in square brackets indicate blocks that can be changed by any inheriting class and the values in `<>` indicate operations that are hard coded in the forward of `BaseEncoderMaskerDecoder`.

As the forward of `DeMask` is written, the input to the mask estimator is not always `tf_rep`. To make it compatible with the `BaseEncoderMaskerDecoder`, we could add a `preprocess_masker_input` between `tf_rep` and `[Masker]` in the base class. Like all the hooks in `BaseEncoderMaskerDecoder`, this would have a default behaviour of returning the data given as input.

**Comment by mpariente** [comment]
`DeMask` was merged in a hurry so the code is not so clean indeed. It's a good thing to clean it up, thanks!

1. This code should probably use `filterbank.n_feats_out` which account for the nyquist frequency in the STFT. About the error, I think it'll be raised in `take_mag`, but we can raise it before as well. 

2. Correct.

> We could add a `preprocess_masker_input`. 

Completely agree, let's add that!

**Comment by mhu-coder** [comment]
Thanks for the inputs!

A quick update about the progress of the work:

- [ x ] Backward compatibility tests for `DeMask`. However, these are commented at the moment as I don't know where I can put the binary data that are required by the tests (model taken from Zenodo, inputs generated by `torch.rand`, outputs generated by original piece of code)
- [ x ] Clean up of `__init__`
- [ x ] Fix masker I/O dimensions when either `input_type` or `output_type` are set to `reim`
- [ x ] Changes to `BaseEncoderMaskerDecoder.forward` to cover what is going on inside `DeMask`:
  - [ x ] Add `preprocess_masker_input` hook
  - [ x ] Add `preprocess_product_input` hook, which processes `tf_rep` before application of `masks`
  - [ x ] Fix `_shape_reconstructed`: we should have tested the length of `size` instead of checking its `ndim` attribute as `ndim` of a `tensor.shape` is always 1
- [ x ] Make `DeMask` inherit from `BaseEncoderMaskerDecoder`
  - [ x ] Remove `forward`
  - [ x ] Rewrite `__init__`
  - [ x ] Override `preprocess_masker_input`, `preprocess_product_input` and `postprocess_masks`
- [   ] Check that recipe still runs

Questions:
1. How do you manage binary files that are needed to run some tests?
2. Can you easily run the recipe to check that it still works or shall I set it up? Given the improvement suggested in #183, I believe that writing an automatic recipe check for `DeMask` on the branch `refactor_demask` would be redundant?

**Comment by mpariente** [comment]
Great ! 
1. What do you mean exactly? 
2. Automatic recipe check is not supported yet, and shouldn't be supported in this PR, I agree. Yes, I can check the recipe myself. 
3. Yes, this will be better. 

We'll work on automated compat tests for pretrained models "soon". What I meant is to check manually that it works: save a random wav file, load old DeMask, forward and save, load new DeMask, make sure it's the same. I trust you with that and I'll double check (in the mean time, we don't have compat tests).

**Comment by mhu-coder** [comment]
> save a random wav file, load old DeMask, forward and save, load new DeMask, make sure it's the same

That's actually what I did. Except that the "random wav file" is actually made of 5 tensors of different shapes and generated randomly using `torch.rand`. Each of these tensors is passed to an old DeMask model and the input and the output are stored on disk. These input/output data are then loaded in the tests that check that changes to the code do not change the output of the model.

> What do you mean exactly?

The only problem with the previous method is that the tests require binary data (DeMask model and I/O tensors) to be loaded from disk. Do you put these data directly in the repo?

> BTW, I'm not 100% sure about `preprocess_product_input`, but we'll see on the PR itself.

Yeah, I am not really satisfied with the solution either. Any alternative is welcome!

**Comment by mpariente** [comment]
See #294 about that question. 

> Yeah, I am not really satisfied with the solution either. Any alternative is welcome!

Please open the PR so we can discuss it there :smiley:
