### ISSUE TITLE
I meet a bug when I run the ConvTasnet 

### ISSUE THREAD

**Issue by yangyan008001** [mpariente/asteroid#300]
## 🐛 Bug

When I run the Conv-Tasnet example, I meet a error as below

  File "/search/odin/yangyan/asteroid/asteroid/masknn/convolutional.py", line 189, in forward
    skip_connection = skip_connection + skip
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

My asteroid version is 0.3.4 

### To Reproduce
Just run the asteroid/egs/wham/ConvTasNet/run.sh on GPUs,you can reproduce the error!

### Expected behavior
When I open the file "asteroid/masknn/convolutional.py" ,I found the skip_connection = torch.tensor([0.0]), which may not be put on GPUs. After fixing that, the error disapear.

### Environment

 - Asteroid Version or commit tag
 - PyTorch Version (e.g., 1.6.0)
 - PyTorchLightning Version
 - Additional info

**Comment by mpariente** [comment]
Thanks for reporting the bug, I'll fix that !

**Comment by mpariente** [comment]
You can try master now, thanks for reporting.

**Comment by yangyan008001** [comment]
OK. The asterorid is the best separation framework I have ever met. I hope to see the implementation of the Google WaveSplit. ~.~

发件人: Pariente Manuel [mailto:notifications@github.com]
发送时间: 2020年11月2日 16:37
收件人: mpariente/asteroid
抄送: YangYan(AI交互事业部_AI交互技术部); Author
主题: Re: [mpariente/asteroid] I meet a bug when I run the ConvTasnet (#300)


You can try master now, thanks for reporting.
