### ISSUE TITLE
Error in testing DPRNN on WHAM dataset

### ISSUE THREAD

**Issue by tramphero** [mpariente/asteroid#310]
After training the DPRNN model on WHAM dataset,  I meet an error during evaluation. The detailed logs of my training and testing are as follow:
**training**
^MValidating:  99%|█████████▉| 266/268 [00:41<00:00,  6.43it/s]^[[A^MEpoch 199: 100%|█████████▉| 1506/1508 [07:17<00:00,  3.44it/s, loss=-18.163, v_num=0, val_loss=-17.2]
^MValidating: 100%|█████████▉| 267/268 [00:41<00:00,  6.40it/s]^[[A^MEpoch 199: 100%|█████████▉| 1507/1508 [07:17<00:00,  3.44it/s, loss=-18.163, v_num=0, val_loss=-17.2]
**testing**
Results from the following experiment will be stored in exp/train_dprnn_sep_clean_8kmin_8c476f50
^M  0%|          | 0/3000 [00:00<?, ?it/s]^M  0%|          | 0/3000 [00:00<?, ?it/s]
Drop 0 utts(0.00 h) from 3000 (shorter than None samples)
Traceback (most recent call last):
  File "eval.py", line 143, in <module>
    main(arg_dic)
  File "eval.py", line 69, in main
    loss, reordered_sources = loss_func(est_sources, sources[None], return_est=True)
  File "/data2/sly.zsl/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data2/sly.zsl/PycharmProjects/SAI/asteroid/losses/pit_wrapper.py", line 98, in forward
    pw_losses = self.loss_func(est_targets, targets, **kwargs)
  File "/data2/sly.zsl/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/data2/sly.zsl/PycharmProjects/SAI/asteroid/losses/sdr.py", line 51, in forward
    assert targets.size() == est_targets.size()
AssertionError

**Environment**
pytorch=1.6.0
torchaudio=0.6.0
pytorch-lightning=1.0.4

**Comment by mpariente** [comment]
Which version of asteroid? Or better, which commit (`git log --pretty=format:'%h' -n 1`)?

I see this happens in the first example on eval. 
Can you relaunch from stage 4 and try to debug to tell me the length of `targets` and `est_targets` please? 
Also, note that we don't support lightning 1+ yet, but I don't think it's related.

**Comment by tramphero** [comment]
> Which version of asteroid? Or better, which commit (`git log --pretty=format:'%h' -n 1`)?
> 
> I see this happens in the first example on eval.
> Can you relaunch from stage 4 and try to debug to tell me the length of `targets` and `est_targets` please?
> Also, note that we don't support lightning 1+ yet, but I don't think it's related.

**Comment by tramphero** [comment]
Thanks ! I reinstall the environment and it is work now.
