### ISSUE TITLE
Provide better error message for impatient people like me

### ISSUE THREAD

**Issue by hbredin** [mpariente/asteroid#325]
Because I did not read the documentation before playing with `asteroid`, I tried this:

```python
filters = ParamSincFB(...)
filters(waveforms)
```
instead of 
```python
filters = Encoder(ParamSincFB(...))
filters(waveforms)
```

Therefore, I got a a not-so-nice `NotImplementedError:` exception without any details.

Would you accept a PR that adds a `forward`  in `Filterbank` base class that raises a `NotImplementedError` that tells impatient people like me that they should wrap filter banks in an `Encoder` or a `Decoder`?

**Comment by mpariente** [comment]
Yes, please ! :smiley:
