### ISSUE TITLE
Why egs/wham/DPTNet/eval.py and egs/wham/DPRNN/eval.py is the same ?

### ISSUE THREAD

**Issue by guiruli08650129** [mpariente/asteroid#330]
#### My Experiments:
I trained the DPTNet model with my own data and tried to evaluate on my testing data.
The result (SI-SDR) is : {"si_sdr": 7.398276868387594, "si_sdr_imp": 7.404194952754807}
Then I modified the code and wanted to restore the DPTNet model to continue training.
And I found that egs/wham/DPTNet/eval.py restored the model with DPRNNTasNet function.

#### My Questions:

1. Why to use DPRNNTasNet function to restore the DPTNet model, and it still working ?
2. I modified the code but got the same result: {"si_sdr": 7.398276868387594, "si_sdr_imp": 7.404194952754807}. Is it correct ?
> ```
> # model = DPRNNTasNet.from_pretrained(model_path)
> model = DPTNet.from_pretrained(model_path)
> ```

Thanks for your reply. :)

**Comment by mpariente** [comment]
Hahah, yes, that's confusing ! 
In the pretrained model format, there is the name of the model, and the _real_ model is retrieved from the base class so that gives the same model in the end. But yes, that's a mistake. 

Would you mind submitting a PR to change it to `DPTNet` please?

**Comment by ashish10alex** [comment]
Hi, 
I am getting similar performance values for DPTNet when testing on LibriMix for noisy speech separation. 
I was wondering why is the performance of DPTNet worse than ConvTasNet and DPRNN
