### ISSUE TITLE
Asteroid conda environment

### ISSUE THREAD

**Issue by mcernak** [mpariente/asteroid#332]
## 🚀 Feature
I suggest managing the project's dependencies using the conda environment.

### Motivation

Conda is a cross-platform management system. Besides, it allows clear separation of different projects on a single computer.

### What you'd like

Create PR. `requirements.txt` would be replaced by `environment.yml.`

### Alternatives

Keep the status quo.

**Comment by mpariente** [comment]
Thanks for raising the issue. 

Do you mean being able to install asteroid with `conda install asteroid`, or just having a `environment.yml` from which a conda env can be created? 

I'm unsure about forcing people to use conda instead of pip..

**Comment by mcernak** [comment]
I meant the latter one; looks to be a better way of managing dependencies. I suggest having `environment.yml` (attached), creating the env by `conda env create -f environment.yml `, and then `conda activate asteroid`. That's it.

I know many developers who love conda as it makes life easier. But you are also right, it is just one way how to manage dependencies.

[environment.yml.txt](https://github.com/mpariente/asteroid/files/5562456/environment.yml.txt)

**Comment by mpariente** [comment]
This is cool indeed and I've had this discussion few times but I still didn't get the answer I'm looking for. 

In the .yml file, it's possible to add `-r requirements.txt` in the `pip` section so if we'd create a `environment.yml` file with only this as content, that would probably work for both pip and conda users. 
If we do that, the all deps are installed with pip, is it a problem? If yes, how? 

I only use conda to install torch and torchaudio. For the rest, I use pip. So I wouldn't see the problem in my case, but not sure about others. 

I know @jonashaag has a tooth against conda, curious to have your opinion.

**Comment by jonashaag** [comment]
> If we do that, the all deps are installed with pip, is it a problem? If yes, how?

It can become a problem because Conda resolves pip installed packages and their dependencies differently from native ones. I think they are working on interoperability but it’s not done yet. So if you’re using Conda you’re probably best off installing as little as possible using pip. 

> I only use conda to install torch and torchaudio. For the rest, I use pip. So I wouldn't see the problem in my case, but not sure about others.

That’s exactly how I do it now because I’ve had a ton of issues with Conda but it’s still better at installing the correct CUDA, Torch, MKL, etc. versions.

**Comment by jonashaag** [comment]
That said, I think maintaining a Conda environment file would be ok, but at this point not all Asteroid dependencies are packaged for Conda, so we’d have to resort to pip for at least some of the dependencies, which doesn’t sound like a lot of fun to maintain...

**Comment by mpariente** [comment]
@mcernak, would you like to make a PR for it?

**Comment by mcernak** [comment]
Sure, PR #354 was created.

The idea is to have an empty environment `asteroid` that will be later populated by pip as before but within the environment.

**Comment by mpariente** [comment]
Closed by #354 
Thanks
