### ISSUE TITLE
Better names in filterbanks.transforms 

### ISSUE THREAD

**Issue by mpariente** [mpariente/asteroid#335]
The conversation started [here](https://github.com/mpariente/asteroid/pull/333#discussion_r526647058), let's move it to an issue for more visibility. 

So, the `transforms.py` file has been here almost untouched since the first draft of Asteroid, and the names in there are not so great. 
Since then `complex_nn.py` has introduced "conflicting" names (`torch_complex_from_magphase` compared to `from_mag_and_phase` in `transform`). 

- `take_reim` is useless, and even confusing. You might expect to receive a tuple of (re, im) when calling it, but you get your input. This was introduced to be used in `Container`, a base class that disappeared since then. 
- `take_cat` is also not as clear as it could be.

### Propositions
1. Remove `take_reim`.
2. Rename `take_mag` to `mag`
3. Rename `take_cat` to `magreim` ???
3. Rename `to_polar` to `magphase`
4. Rename `from_mag_and_phase` to `from_magphase`
5. Keep `apply_*_mask`
6. Keep all in `complex_nn` untouched
7. Introduce `reim` that returns `(real, imag)` tuple? 

Of course, this means deprecating things properly.

**Comment by popcornell** [comment]
Makes sense for me

**Comment by jonashaag** [comment]
For reference, in torchaudo there are

- `magphase(x) -> (mag(x), angle(x))`
- `angle(x)` and `complex_norm(x)` (= `mag`)

and in Torch there are

- `.angle()`
- `.abs()`

🙄

I don't really have an opinion on the names other than we should not introduce multiple names in Asteroid in addition to the Torch names :-D

**Comment by mpariente** [comment]
We could have `angle`, but then `magphase` is weird, why not `magangle`?
OTOH, `abs` is not appropriate IMO (but it is for native tensors).

**Comment by mpariente** [comment]
Closed in #342
