### ISSUE TITLE
About training DCCRNet

### ISSUE THREAD

**Issue by Tigerwww** [mpariente/asteroid#341]
### A fresher wants to train DCCRNet

Hi, sorry to bother you. 

I'm a beginner studying voice conversion, however, I need a denoising model.

I'm planning to train DCCRNet on my own dataset, but I just found no files like run.sh in the DCCRNet recipe. So I need to write it?

And How much time it may take with only one Titan RTX?

Very thanks for answering.

**Comment by jonashaag** [comment]
Duplicate of #278. Feel free to continue there if you have more questions!
