### ISSUE TITLE
Migrate to asteroid-filterbanks

### ISSUE THREAD

**Issue by mpariente** [mpariente/asteroid#345]
Now that [asteroid-filterbanks](https://github.com/asteroid-team/asteroid-filterbanks) has been released, we should migrate to it :tada: 

Few points:
- Backward compat: this is straightforward, I guess a simple `import asteroid_filterbanks as filterbanks` with `asteroid/__init__.py` will do perfectly. 
- Source code: Two options (not sure myself)
  - Consider that `asteroid.filterbanks` is still a thing and keep using it. 
  - Replace everything from `asteroid.fitlerbanks` to `asteroid-filterbanks` to give the "good example".
- CI: specific unit tests for filterbanks will be done there but we'll keep some non-specific tests here. This is cool because it'll probably drive us to do more thorough testing of the filterbanks themselves, and that's a good point. 
- Docs: that the trickiest IMO. The docs will still be hosted on asteroid's docs so we have to find a way to make it nicely. Didn't find this out yet, any help deeply appreciated.

**Comment by jonashaag** [comment]
> * Replace everything from `asteroid.fitlerbanks` to `asteroid-filterbanks` to give the "good example".

I think we should it this but, but don't really have any good reasons for that. Except for maybe that my experience is that these aliased imports can sometimes cause trouble for people importing them (but don't have any concrete examples right now)



> * we'll keep some non-specific tests here

This makes sense, and I think we should also add a new CI configuration for testing with the master version of `asteroid_filterbanks`, as is common with essential third-party dependencies, to be aware of future (next release of `asteroid_filterbanks`) breakage.

**Comment by mpariente** [comment]
> I think we should also add a new CI configuration for testing with the master version of asteroid_filterbanks

Yes, totally.

**Comment by mpariente** [comment]
For the docs, it's easier than I thought. 

In the current `filterbank.rst` file, I can change `asteroid.filterbanks` by `asteroid_filterbanks` and this will retrieve the class and autodoc it. 
This is really cool ! 

One downside of this is that the rst file is in asteroid, not in asteroid-filterbanks. This means making a two step process for adding a feature to asteroid-filterbank and adding the docs in asteroid. Ideally, we could do better. However, it's not meant to change that often and it's probably fine. 

Two other options I imagined that would have the docs folders in `asteroid-filterbanls` (so that it doesn't have the flaws of the previous method) but didn't explore yet: 
- Having `asteroid-filterbanks` as a submodule
- Cloning `asteroid-filterbanks` during the docs build process

I personally think that the first one is fine, given the state of things.

**Comment by mpariente** [comment]
Another question: What should we do with `ebased_vad`, `compute_delta` and `concat_deltas` which are not linked to asteroid complex-like tensors? 
Maybe move to `asteroid.dsp`? 
@popcornell your insight would also be nice here.

**Comment by mpariente** [comment]
Closed by #346
