### ISSUE TITLE
CLI docs broken

### ISSUE THREAD

**Issue by jonashaag** [mpariente/asteroid#356]
https://mpariente.github.io/asteroid/cli.html

I'll try to fix this. Probably need to install Asteroid first.

**Comment by mpariente** [comment]
Apparently the problem is still there. 
![image](https://user-images.githubusercontent.com/18496796/100275065-af0a0480-2f5f-11eb-8fbb-e8df6a778379.png)

**Comment by mpariente** [comment]
Ok, problem solved, sorry, it needed time. 

![image](https://user-images.githubusercontent.com/18496796/100275336-0b6d2400-2f60-11eb-9fdb-223f60b2ca65.png)

I don't know why the warning is triggered though
