### ISSUE TITLE
Yet another problem

### ISSUE THREAD

**Issue by hadaso** [mpariente/asteroid#40]
Hi again,
Trying to download and install dns_challenge data.
After updating your last fix, i'm in this status:
![Screenshot from 2020-03-05 15-20-22](https://user-images.githubusercontent.com/55354058/75987951-7d489d80-5ef9-11ea-9634-9ecdc2343f3b.png)
I would appreciate any assistance.

**Comment by mpariente** [comment]
Hi, thanks for reporting the issue. 
This should be fixed now. 
Please that for the remaining of the recipe to work, you should have a working python installation with `asteroid` installed already.

**Comment by hadaso** [comment]
now i am getting this message:
![Screenshot from 2020-03-09 13-22-25](https://user-images.githubusercontent.com/55354058/76208840-27ca0480-6209-11ea-99ca-f4f747501496.png)
Is this related to the asteroid installation?
I have python installed on this computer, and astroid ver 2.1.0 (astroid, not asteroid, is that what you meant?).

**Comment by mpariente** [comment]
This is not related to `asteroid`, this was a mistake in a bash script that I fixed.
Please, pull the repository again with the new fix, and install `asteroid`, see the [instructions](https://github.com/mpariente/asteroid#installation).

**Comment by hadaso** [comment]
Worked my way to running Stage 2, but then this...
![Screenshot from 2020-03-11 08-54-08](https://user-images.githubusercontent.com/55354058/76390539-4568ac80-6376-11ea-8ac3-92a49653bc6f.png)
Any ideas what I should do?

**Comment by mpariente** [comment]
Thanks for your feedback. This is not related to Asteroid. 
> Any ideas what I should do?
Please Google it, you'll most probably find a fix, and start from stage 2 again.

**Comment by mpariente** [comment]
Did you solve your problems? Could you go on with the recipe?

**Comment by hadaso** [comment]
No. I got tired of trying to get it to work.
Your repository is not documented enough. Not for me anyway.
My initial goal was to use the 'train.py' file to train the NSNet, but now i'm not sure if it is related at all. Don't want to waste my time.

**Comment by mpariente** [comment]
Sorry you had to experience some problems with the path at the beginning, the recipe was not stable enough yet. 
That's too bad because we try to write in-line comments in the recipes to help users. 
I'll close this issue, feel free to re-open it if you have some more questions.

By the way, we don't have an implementation of NSNet here yet. Feel free to contribute if you'd like to make our repo better.
