### ISSUE TITLE
Asteroid paper as Interspeech 2020

### ISSUE THREAD

**Issue by mpariente** [mpariente/asteroid#69]
Dear Asteroid contributors @popcornell @JorisCos @sunits @mhu-coder @jensheit @etzinis @mdjuamart @Ariel12321 @dditter @michelolzam (Future contributors : @faroit)

We intend to submit a paper describing Asteroid to Interpseech 2020 (deadline is May 8th) and as contributors, it seems logic that you appear as co-authors on the paper. You'll be asked to proof-read the final version of the paper, but I guess this is normal. Also, you are welcome to help in any way for the paper, just let me know if you'd like to. 

Could you please provide me with your full name and affiliations please (if there are special characters, I'd appreciate the TeX code for it.)? You can do it here or send me an email. 

Thanks !

**Comment by faroit** [comment]
@mpariente great. When do you want to freeze the features? I guess for a regular conference paper we could add more things after submission (unlike e.g. JOSS)

**Comment by mpariente** [comment]
Maybe this answers the question, or maybe I didn't understand it.
These are the things we'll add by the deadline most probably 
- Deep clustering recipe + results (maybe Chimera and Chimera++)
- Two-step mask learning recipe + results
- DPRNN results
- MUSDB dataset
- Open unmix recipe + results
- FUSS dataset
- Some model recipe on FUSS + results
- Libri{2,3}mix train, val, test  sets
- VCTK{2,3}mix test set
- Wavesplit recipe (that's not sure yet)
- Multiphase Gammatone filterbank (also not sure)

If I didn't answer the question, feel free to reformulate.

**Comment by mpariente** [comment]
Thanks to all the contributors, the paper has been submitted (should be announced in arxiv tomorrow).
